# Site settings
title: Adnan Shahnawaz
email: unavailable
description: > # this means to ignore newlines until "baseurl:"
  HELLO!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: unavailable
github_username:  unavailable

# Build settings
markdown: kramdown
