# Site settings
title: Danyal Maruf
email: Danyal68@hotmail.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Hello, My name is Danyal, and apparently I am a legend.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
Instagram_username: Danny_Maruf 
Facebook_username:Danyak Maruf

# Build settings
markdown: kramdown
